<?php foreach($this->messages as $message) { ?>
    <div class="center blue block flash"><?php echo $message ?>
        <a href="#" class="float-right close">
            <img src="<?php echo $this->basePath('img/close.png') ?>" alt="Close" />
        </a></div>
<?php }?>
    <div class="center user_creation">
        <form action="/user/create" method="post">
            <label for="nick">Nickname :</label><br><input type="text" name="nick" value="<?php echo htmlentities($this->nickname); ?>" /><br>
            <label for="login">Login :</label><br><input type="text" name="login" value="<?php echo htmlentities($this->login); ?>" /><br>
            <label for="pass1">Password : </label><br><input type="password" name="pass1" /><br>
            <label for="pass2">Repeat : </label><br><input type="password" name="pass2" /><br>
            <input class="center" type="submit" value="create" />
        </form>
    </div>
