<?php foreach($this->messages as $message) { ?>
    <div class="center blue block flash"><?php echo $message ?>
        <a href="#" class="float-right close">
            <img src="<?php echo $this->basePath('img/close.png') ?>" alt="Close" />
        </a></div>
<?php }?>

<form action="/user/create" method="post">
	nickname : <input type="text" name="nick" value="<?php echo $this->nickname; ?>" style="border:1px solid red" /><br />
	login : <input type="text" name="login" value="<?php echo $this->login; ?>" style="border:1px solid red" /><br />
	password : <input type="password" name="pass1" style="border:1px solid red" /><br />
	repeat : <input type="password" name="pass2" style="border:1px solid red" /><br />
	<input type="submit" value="create" />
</form>