<form action="/user/update" method="post">
	<table border="0" cellspacing="0" cellpadding="0" class="user_home">
		<tr>
			<td>
				<img src="<?php echo $this->basePath('img/big_user.png') ?>" alt="User" />
			</td>
			<td>
				<p>
					<label>Login : <br />
					<input type="text" name="login" value="<?php echo htmlentities($this->login); ?>" /></label>
				</p>
				<p>
					<label>Nickname : <br />
					<input type="text" name="nick" value="<?php echo htmlentities($this->nickname); ?>" /></label>
				</p>
				<p>
					<span class="user_notice">Leave blank to not change password</span><br />
					<label>Password : <br />
					<input type="password" name="pass1" /><br /> </label>
					<label>Repeat password : <br />
					<input type="password" name="pass2" /><br /></label>
				</p>
				<input type="submit" value="Update your account" />
			</td>
		</tr>
	</table>
</form>

