<form action="/user/update" method="post">
	<table border="0" cellspacing="0" cellpadding="0" class="user_home">
		<tr>
			<td>
				<img src="<?php echo $this->basePath('img/big_user.png') ?>" alt="User" />
			</td>
			<td>
				<p>
					Login : <br />
					<input type="text" name="login" value="<?php echo $this->login; ?>" />
				</p>
				<p>
					Nickname : <br />
					<input type="text" name="nick" value="<?php echo $this->nickname; ?>" />
				</p>
				<p>
					<span class="user_notice">Leave blank to not change password</span><br />
					Password : <br />
					<input type="password" name="pass1" /><br />
					Repeat password : <br />
					<input type="password" name="pass2" /><br />
				</p>
				<input type="submit" value="Update your account" />
			</td>
		</tr>
	</table>
</form>

