<ul>
	<li>Controller : User</li>
	<li>Action : Update</li>
</ul>
<form action="/user/update" method="post">
	nickname : <input type="text" name="nick" value="<?php echo $this->nickname; ?>" style="border:1px solid red" /><br />
	login : <input type="text" name="login" value="<?php echo $this->login; ?>" style="border:1px solid red" /><br />
	Leave blank to not change password :<br />
	password : <input type="password" name="pass1" style="border:1px solid red" /><br />
	repeat : <input type="password" name="pass2" style="border:1px solid red" /><br />
	<input type="submit" value="update" />
</form>