<!-- Temporary info section
<ul>
	<li>Controller : Thread</li>
	<li>Action : Index</li>
	<li>Search : <?php echo $this->search; ?></li>
	<li>Logged user : <?php echo ($this->user != null ? $this->user->nickname : '&lt;aucun&gt;'); ?></li>
</ul>
-->

<section id="main">

	<?php if ($this->user == null) { ?>
		<div class="center blue block flash"> Please login to ask a question.
            <a href="#" class="float-right close">
                <img src="<?php echo $this->basePath('img/close.png') ?>" alt="Close" />
            </a>
        </div>
	<?php } else { ?>
		<div class="block new_form">
			<a class="center" >Ask your question !</a>
			<form action="/thread/create" method="post">
				<label for="title">Title :</label><input type="text" name="title" value="<?php echo $this->newTitle; ?>" />
				<label for="question">Question :</label><textarea name="question"  rows="4" cols="60"><?php echo $this->newQuestion; ?></textarea>
				<label for="tags">Tags :</label><input type="text" name="tags" value="<?php echo $this->newTags; ?>" />
				<input class="center" type="submit" value="Send" />
			</form>
		</div>
	<?php } ?>

	<?php foreach($this->messages as $message) { ?>
        <div class="center blue block flash"><?php echo $message ?>
            <a href="#" class="float-right close">
                <img src="<?php echo $this->basePath('img/close.png') ?>" alt="Close" />
            </a></div>
	<?php }?>

	<?php if ($this->infoBoxVisibility == 'show')
		echo $this->partial('layout/infoBox', array()); ?>

	<section class="half float-left">
		<div class="center"> <img src="<?php echo $this->basePath('img/fine.png'); ?>" alt="Fine" /> </div>

		<?php foreach($this->threadListSolved as $thread) { ?>
			<a class="thread block green" href="/post/index/<?php echo $thread->id ?>">
				<h1> <?php echo $thread->title ?> </h1>
				<div class="vote"><?php echo $thread->mainPost->getVoteSum() ?> <span>votes</span></div>
				<div class="information">
					<div class="author">
						Post&eacute; par <span><?php echo $thread->mainPost->user->nickname ?></span>
						le <?php echo $thread->mainPost->date->format('d.m.Y \&\a\g\r\a\v\e; H:i:s') ?>
					</div>
					<div class="tag">
						<?php foreach($thread->tags as $tag) { ?>
							<span><?php echo $tag->name ?></span>
						<?php } ?>
					</div>
				</div>
				<hr class="clear" />
			</a>
		<?php } ?>
	</section>
	<section class="half float-left">
		<div class="center"> <img src="<?php echo $this->basePath('img/panic.png'); ?>" alt="Panic" /> </div>
		<?php foreach($this->threadListUnsolved as $thread) { ?>
			<a class="thread block red" href="/post/index/<?php echo $thread->id ?>">
				<h1> <?php echo $thread->title ?> </h1>
				<div class="vote"><?php echo $thread->mainPost->getVoteSum() ?> <span>votes</span></div>
				<div class="information">
					<div class="author">
						Post&eacute; par <span><?php echo $thread->mainPost->user->nickname ?></span>
						le <?php echo $thread->mainPost->date->format('d.m.Y \&\a\g\r\a\v\e; H:i:s') ?>
					</div>
					<div class="tag">
						<?php foreach($thread->tags as $tag) { ?>
							<span><?php echo $tag->name ?></span>
						<?php } ?>
					</div>
				</div>
				<hr class="clear" />
			</a>
		<?php } ?>
	</section>
	<hr class="clear" />
	<div class="center more"><a href="#">Afficher plus</a></div>
</section>
