<?php // infoBox.phtml ?>
<section id="infoBox" class="block blue">
    <a href="#" class="float-right close">
        <img src="<?php echo $this->basePath('img/close.png') ?>" alt="Close" />
    </a>
    <h1> About ArcAnswer</h1>
    <p>You have a question about programming, a problem with your code ?
        You're at the right place ! Check if your problem has already
        been solved or posted. Otherwise, feel free to ask :) Some nerd
        will know the answer. You can vote or comment other posts, mark
        your post as solved, and many more thing that will make your coding
        life more shiny.
        <br />
        <br />
        See you soon !
    </p>
</section>