<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate('ArcAnswer'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<!-- Meta Data -->
	<?php echo $this->headMeta()
		->appendName('description', $this->translate('ArcAnswer Description'))
		->appendName('keywords', $this->translate('ArcAnswer Keywords'))
		->appendName('author', 'Chavaillaz Johan, Kuhner David, Racine Jason')
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'))
		->prependStylesheet($this->basePath().'/css/design.css')
		->prependStylesheet($this->basePath().'/fonts/lato/stylesheet.css')
		->prependStylesheet($this->basePath().'/plugins/chosen/chosen.dark.css')
	?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath().'/js/jquery.min.js')
		->appendFile($this->basePath().'/js/global.js')
		->appendFile($this->basePath().'/plugins/chosen/chosen.jquery.min.js')
		->appendFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->appendFile($this->basePath().'/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
	?>

</head>
<body>
	<header>
		<div class="main">
			<a href="<?php echo $this->url('home') ?>" class="float-left name">
				<img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Logo" class="logo" />
				<h1><?php echo $this->translate('ArcAnswer') ?></h1>
			</a>
				<span class="float-right user dark-select">
					<select id="orderBy" name="order_by">
						<option value="date"><?php echo $this->translate('Order by date') ?></option>
						<option value="vote" selected="selected"><?php echo $this->translate('Order by vote') ?></option>
					</select>
				</span>
			<form action="#" method="post" class="center">
				<input type="text" name="search" value="" class="searchInput" />
				<input type="submit" name="submit" value="" class="searchButton" />
			</form>
		</div>
	</header>
	<section id="main">
		<?php echo $this->content; ?>
	</section>
	<footer>
		<div class="main">
			<span class="float-right">
				J. Chavaillaz, D. Kuhner, J. Racine
			</span>
			<a href="http://www.he-arc.ch">
				Haute Ecole Arc
			</a>
		</div>
	</footer>
	<?php echo $this->inlineScript() ?>
</body>
</html>
