<?php echo $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle($this->translate('ArcAnswer'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<!-- Meta Data -->
	<?php echo $this->headMeta()
		->appendName('description', $this->translate('ArcAnswer Description'))
		->appendName('keywords', $this->translate('ArcAnswer Keywords'))
		->appendName('author', 'Chavaillaz Johan, Kuhner David, Racine Jason')
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'))
		->prependStylesheet($this->basePath().'/css/design.css')
		->prependStylesheet($this->basePath().'/fonts/lato/stylesheet.css')
		->prependStylesheet($this->basePath().'/plugins/chosen/chosen.dark.css')
	?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath().'/js/jquery.min.js')
		->appendFile($this->basePath().'/js/global.js')
		->appendFile($this->basePath().'/plugins/chosen/chosen.jquery.min.js')
		->appendFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->appendFile($this->basePath().'/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
	?>

</head>
<body>
	<header>
		<div class="main">
			<a href="<?php echo $this->url('home') ?>" class="float-left name">
				<img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Logo" class="logo" />
				<h1><?php echo $this->translate('ArcAnswer') ?></h1>
			</a>
				<span class="float-right user dark-select">
					<a id="dropdown_icon" class="user_icon" onclick="dropdown_showHide('#dropdown_icon', '#dropdown_content'); return false;">
						<img src="<?php echo $this->basePath('img/user.png') ?>" alt="User" />
					</a>
					<div id="dropdown_content">
						<div>
							<?php
							if ($this->GLOBAL_AUTH->getIdentity() == null) { ?>
								<form action="/user/login" method="post">
									<table border="0" cellspacing="0" cellpadding="2">
										<tr>
											<td>Login :</td>
											<td><input type="text" name="login" /></td>
										</tr>
										<tr>
											<td>Password :</td>
											<td><input type="password" name="password" /></td>
										</tr>
									</table>
									<input type="submit" value="Connexion" /> <span class="or">OR</span> <a href="/user/create">Create an account</a>
								</form>
							<?php } else { ?>
								<a href="/user/logout">Disconnect</a><br />
								<a href="/user/index">Show profile</a>
							<?php } ?>
						</div>
					</div>
					<select id="orderBy" name="order_by">
						<option value="date"><?php echo $this->translate('Order by date') ?></option>
						<option value="vote" selected="selected"><?php echo $this->translate('Order by vote') ?></option>
					</select>
				</span>
			<form action="/thread/index" method="post" class="center">
				<input type="text" name="search" value="" class="searchInput" />
				<input type="submit" name="submit" value="" class="searchButton" />
			</form>
		</div>
	</header>
	<section id="main">
		<?php echo $this->content; ?>
	</section>
	<footer>
		<div class="main">
			<span class="float-right">
				J. Chavaillaz, D. Kuhner, J. Racine
			</span>
			<a href="http://www.he-arc.ch">
				Haute Ecole Arc
			</a>
		</div>
	</footer>
	<?php echo $this->inlineScript() ?>
</body>
</html>
